## 결과 부족이 발생할 경우 null과 Failure를 사용하라
* 일단 예외는 정보를 전달하는 방법으로 사용해서는 안 됩니다.
* 예외가 전파되는 과정을 제대로 추적하지 못합니다.
* 코틀린의 모든 예외는 unchecked 예외입니다.
* 예외는 예외적인 상황을 처리하기 위해서 만들어졌으므로 명시적인 테스트만큼 빠르게 동작하지 않습니다.
* try-catch 블록 내부에 코드를 배치하면, 컴파일러가 할 수 있는 최적화가 제한됩니다.

```kotlin 
inline fun <reified T> String.readObjectOrNull() : T? {
	//...
    if(incorrecSign) {
    	return null
    }
    
    //...
    return result
}

inline fun <reified T> String.readObject() : Result<T> {
	//...
    if(incorrectSign) {
    	return Failure(JsonParsingException())
    }
    //...
    return Success(result)
}

sealed class Result<out T>
class Success<out T>(val result: T) : Result<T>()
class Failure(val throwable : Throwable) : Result<Nothing>()

class JsonParsingException: Exception()
````
null과 Failure는 예상되는 오류를 표현할 때 굉장히 좋습니다. 이는 명시적이고, 효율적이며, 간단한 방법으로 처리할 수 있습니다.