# Item 7 : Prefer null or Failure result when the lack of result is possible

때때로 함수에서 원하는 결과를 얻을 수 없는 상황이 생길 수 있으며, 이를 처리하는 2가지 메커니즘이 존재한다.

- `null` / `sealed class` 반환
- Throw an exception

Exception(이하 예외)는 정보 전달 목적으로 사용되는 것이 아닌, 예외 조건에 부합될 때 사용되어야 한다. 그 이유는 아래와 같다.

- 예외가 전파되는 방식은 대부분 가독성이 떨어지기에, 예외 조건에 부합될 때 사용되어야 한다.
- 컴파일러가 예외 처리를 강제하지 않아, 예외 조건을 알 수 없는 경우가 많기에, 예외 조건이 명확할 때 사용되어야 한다.
- JVM 환경에서 예외는 예외적인 상황을 위해 설계 되어, 예외 처리 시 여러 비용들이 발생하기에 명시적인 테스트들('if', 'when' 등 조건문)만큼 효율적이지 않아, 예외 조건에 부합될 때 사용되어야 한다.
- 'try-catch' 블록 안에 코드를 배치하면 컴파일러가 수행하는 최적화를 방해하므로, 예외 조건에 부합될 때 사용되어야 한다.

반면, `null` or `Failure`은 명시적이기에 예상 가능한 오류를 처리하는데 적합하다.

- 오류가 예상될 때, `null` or `Failure` 반환
- 오류가 예상 되지 않을 때, 예외 throw

```kotlin
sealed class Result<out T> {
    data class Success<out T>(val result: T) : Result<T>()
    data class Failure(val throwable: Throwable) : Result<Nothing>()
}

class JsonParsingException : Exception()

inline fun <reified T> String.readObjectOrNull(): T? {
    // ...
    if (incorrectSign) {
        return null
    }
    // ...
    return result
}

inline fun <reified T> String.readObject(): Result<T> {
    // ...
    if (incorrectSign) {
        return Failure(JsonParsingException())
    }
    // ...
    return Success(result)
}
```

위와 같은 방식으로 처리되는 오류는 다루기 쉽고, 오류 상황을 쉽게 인지할 수 있다.

Kotlin에서는 `null`을 처리하기 위해 'Safe-call' or 'Elvis 연산'을 지원하고,
`Result`와 같은 'Union type'의 경우 `when`을 통해 쉽게 처리할 수 있게 지원한다.

```kotlin
val age = userText.readObjectOrNull<Person>()?.age ?: -1

val age =
    when (val person = userText.readObject<Person>()) {
        is Success -> person.age
        is Failure -> -1
    }
```

만약 `try-catch` 만을 사용하여 예외 처리를 했을 때, 잘못하여 예외를 놓치게 되면 앱 전체가 중단될 위험이 있다.  
반면, `null` or `sealed class`는 명시적인 처리가 필요하지만 앱을 중단 하지 않는다.  
이런 이유로, `null` or `sealed class`를 사용하여 오류를 처리하는 방식이 `try-catch` 보다 더 효율적이고, 명시적이다.

추가로, `sealed class`는 계속해서 서브 클래스를 확장할 수 있기에 정보를 계속해서 추가해야 하는 경우 유용하다.
그렇지 않은 경우에는 `null`을 사용하는 것이 좋다.
